### ISSUE TITLE
Issue when MFA is required

### ISSUE THREAD

**Issue by cjhubert** [awslabs/amazon-ecr-credential-helper#180]
Currently running into an issue where having `mfa_serial` in the aws credentials file leads to the following error:

```
AWS_SDK_LOAD_CONFIG=true AWS_PROFILE=profile1 docker pull <aws_account_id>.dkr.ecr.us-east-2.amazonaws.com/<repo>:<tag>
Error response from daemon: Get https://<aws_account_id>.dkr.ecr.us-east-2.amazonaws.com/v2/<repo>/manifests/<tag>: no basic auth credentials
```

Below are the settings used for the environment. If `mfa_serial` is removed and the MFA requirement on actions removed, the docker pull works fine. As soon as `mfa_serial` is added, however, it stops working.

`~/.docker/config.json`
```
{
    "credHelpers": {
        "<aws_account_id>.dkr.ecr.us-east-2.amazonaws.com": "ecr-login"
    }
}
```

`~/.aws/credentials`
```
[default]
aws_access_key_id = <access_key>
aws_secret_access_key = <secret>

[profile1]
source_profile=default
region=us-east-2
role_arn=<readrole_arn>
mfa_serial=<mfa_arn>
```

**Comment by jeremygaither** [comment]
Same here. Tried while using aws-vault for MFA, and it didn't pick up the session info...

**Comment by samuelkarp** [comment]
Hi @cjhubert and @jeremygaither! I haven't tried using the credential helper with `mfa_serial` and I'm not sure whether it will work today.  The credential helper should write logs to `~/.ecr/log/ecr-login.log`; can you look in there and paste the output that is written there when this fails?

(I'm suspecting that this is failing as the credential helper has no way to prompt for an MFA code and I don't believe that the AWS SDK reads from the CLI cache by default.)

**Comment by jeremygaither** [comment]
@samuelkarp I don't see anything under `~/.ecr/log/ecr-login.log`. There's not even an `.ecr` folder in my home folder.

**Comment by khurrammalik** [comment]
I am having a similar issue, here is my output from ~/.ecr/log/ecr-login.log
```
time="2019-09-24T15:01:02-04:00" level=debug msg="Retrieving credentials" region=us-east-1 registry=*********** serverURL=***********.dkr.ecr.us-east-1.amazonaws.com
time="2019-09-24T15:01:02-04:00" level=debug msg="Calling ECR.GetAuthorizationToken" registry=***********
time="2019-09-24T15:01:02-04:00" level=error msg="Error retrieving credentials" error="ecr: Failed to get authorization token: AssumeRoleTokenProviderNotSetError: assume role with MFA enabled, but AssumeRoleTokenProvider session option not set."
```

**Comment by littleJabiel** [comment]
I have the same problem, do you know any workaround please?

thank you

**Comment by simon-weber** [comment]
If you have a valid cache this sort of works:
```
[profile hacky-ecr]
credential_process = cat ~/.aws/cli/cache/*.json  | jq '.Credentials + {Version: 1}'
```

```
AWS_SDK_LOAD_CONFIG=true AWS_PROFILE=hacky-ecr docker pull ...
```

I imagine you'd need to do something more sophisticated to handle multiple roles/accounts, though.

**Comment by awilkins** [comment]
The key bit is in `factory.go` where there are 2 calls to `session.NewSessionWithOptions()`

The API has a slot for `AssumeRoleTokenProvider` which is just a `func() (string, error)` that returns the MFA token as a string, but the cred helper doesn't populate this slot in the call, so if you use a profile that has `mfa_serial` set it will error with

```
~ via 🐹 v1.15.2 on ☁️  dev-account(eu-west-2) 
❯ docker pull 999999999999.dkr.ecr.eu-west-2.amazonaws.com/aws/codebuild/standard:1.0
panic: AssumeRoleTokenProviderNotSetError: assume role with MFA enabled, but AssumeRoleTokenProvider session option not set.

goroutine 1 [running]:
github.com/aws/aws-sdk-go/aws/session.Must(...)
	/home/awilkins/gocode/src/github.com/awslabs/amazon-ecr-credential-helper/ecr-login/vendor/github.com/aws/aws-sdk-go/aws/session/session.go:322
github.com/awslabs/amazon-ecr-credential-helper/ecr-login/api.DefaultClientFactory.NewClientFromRegion(0xc0000b2225, 0x9, 0x5, 0xc0000c2460)
	/home/awilkins/gocode/src/github.com/awslabs/amazon-ecr-credential-helper/ecr-login/api/factory.go:91 +0x334
github.com/awslabs/amazon-ecr-credential-helper/ecr-login.ECRHelper.Get(0x90dd80, 0xb244f0, 0xc0000b2210, 0x2c, 0xc000113c48, 0x45008f, 0xc0000b2210, 0xc000118500, 0x2c, 0xc0000b2210)
	/home/awilkins/gocode/src/github.com/awslabs/amazon-ecr-credential-helper/ecr-login/ecr.go:63 +0x505
github.com/docker/docker-credential-helpers/credentials.Get(0x90d100, 0xc000097410, 0x906c80, 0xc0000ba000, 0x906ca0, 0xc0000ba008, 0xc000097410, 0x7ff98d151998)
	/home/awilkins/gocode/src/github.com/awslabs/amazon-ecr-credential-helper/ecr-login/vendor/github.com/docker/docker-credential-helpers/credentials/credentials.go:130 +0x1f7
github.com/docker/docker-credential-helpers/credentials.HandleCommand(0x90d100, 0xc000097410, 0x7fff1507225a, 0x3, 0x906c80, 0xc0000ba000, 0x906ca0, 0xc0000ba008, 0xc000113f48, 0xc000097410)
	/home/awilkins/gocode/src/github.com/awslabs/amazon-ecr-credential-helper/ecr-login/vendor/github.com/docker/docker-credential-helpers/credentials/credentials.go:73 +0x125
github.com/docker/docker-credential-helpers/credentials.Serve(0x90d100, 0xc000097410)
	/home/awilkins/gocode/src/github.com/awslabs/amazon-ecr-credential-helper/ecr-login/vendor/github.com/docker/docker-credential-helpers/credentials/credentials.go:58 +0x1c5
main.main()
	/home/awilkins/gocode/src/github.com/awslabs/amazon-ecr-credential-helper/ecr-login/cli/docker-credential-ecr-login/main.go:45 +0x14e
Error response from daemon: Get https://999999999999.dkr.ecr.eu-west-2.amazonaws.com/v2/aws/codebuild/standard/manifests/1.0: no basic auth credentials
```

What is probably could do with is ...

- Reading the config to work out whether the current profile has a an `mfa_serial`
- Some kind of config that maps each combo of profile-name and `mfa_serial` to a token provider + key alias 
- A way to return a code from each

The very base would be adding a basic function that prompts for MFA.

e.g. here's my very basic provider for my Yubikey, I patched the source locally to pass this to both those calls.

```go
	awsSession := session.Must(session.NewSessionWithOptions(session.Options{
		SharedConfigState:       loadSharedConfigState(),
		AssumeRoleTokenProvider: YubikeyTokenProvider{KeyName: "mykeyname"}.Provide,
	}))
```
```go
package api

import (
	"os/exec"
	"strings"
)

type YubikeyTokenProvider struct {
	KeyName string
}

func (p YubikeyTokenProvider) Provide() (string, error) {

	cmd := exec.Command("ykman", "oath", "code", "-s", p.KeyName)

	if output, err := cmd.Output(); err != nil {
		return "", err
	} else {
		totpCode := string(output)
		totpCode = strings.TrimSpace(totpCode)
		return totpCode, nil
	}

}
```

**Comment by omus** [comment]
Using [`aws-vault`](https://github.com/99designs/aws-vault) will workaround the lack of MFA support in the ECR credential helper. This works by having `aws-vault` prompt for the MFA token and generating a temporary AWS session credentials.

```sh
aws-vault exec <profile> -- docker pull ...
```

This approach works with the ECR credential helper version 0.6.0 and should be a reasonable approach for those using multiple profiles.

**Comment by kzys** [comment]
@awilkins Thanks for the YubiKey example. In this case, doesn't `ykman` need to access the stdin, which is connected to a user's terminal? That is the blocker @samuelkarp mentioned above. Docker's CLI is calling this helper and the helper cannot take input from the user.

@omus Using aws-valut (or something that is calling Docker's CLI) looks workable. I think having that in README.md may be better than supporting MFA directly on the helper.
