### ISSUE TITLE
EOFError instead of Token prompt when used with aws-okta-processor

### ISSUE THREAD

**Issue by aleskiontherun** [awslabs/amazon-ecr-credential-helper#228]
We are using [aws-okta-processor](https://github.com/godaddy/aws-okta-processor) to authenticate users. ECR access works fine when the session is already established, but initial authentication fails.

So this works fine:
```
# Remove any cached sessions
rm -rf ~/.aws/boto/cache ~/.aws-okta-processor/cache

# Run any AWS command (also works with Ansible, Terraform, etc, but not with docker)
AWS_PROFILE=my-profile aws sts get-caller-identity

# Enter Okta password

# Enter Okta token

# Pull image from ECR
AWS_SDK_LOAD_CONFIG=true AWS_PROFILE=my-profile docker pull ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${REPOSITORY_NAME}:${IMAGE_TAG}
```

But this does not:
```
# Remove any cached sessions
rm -rf ~/.aws/boto/cache ~/.aws-okta-processor/cache

# Pull image from ECR
AWS_SDK_LOAD_CONFIG=true AWS_PROFILE=my-profile docker pull ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${REPOSITORY_NAME}:${IMAGE_TAG}

# Enter Okta password
```

After entering Okta password we get the following error:
```
Password:
Info: Calling https://company-name.okta.com/api/v1/authn
Token: Traceback (most recent call last):
  File "/usr/local/bin/aws-okta-processor", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/aws_okta_processor/cli.py", line 74, in main
    command.run()
  File "/usr/local/lib/python3.7/site-packages/aws_okta_processor/commands/authenticate.py", line 74, in run
    credentials = self.authenticate()
  File "/usr/local/lib/python3.7/site-packages/aws_okta_processor/commands/authenticate.py", line 68, in authenticate
    credentials = saml_fetcher.fetch_credentials()
  File "/usr/local/lib/python3.7/site-packages/aws_okta_processor/core/fetcher.py", line 38, in fetch_credentials
    credentials = super(SAMLFetcher, self).fetch_credentials()
  File "/Users/dizeee/Library/Python/3.7/lib/python/site-packages/botocore/credentials.py", line 629, in fetch_credentials
    return self._get_cached_credentials()
  File "/Users/dizeee/Library/Python/3.7/lib/python/site-packages/botocore/credentials.py", line 639, in _get_cached_credentials
    response = self._get_credentials()
  File "/usr/local/lib/python3.7/site-packages/aws_okta_processor/core/fetcher.py", line 62, in _get_credentials
    no_okta_cache=self._configuration["AWS_OKTA_NO_OKTA_CACHE"]
  File "/usr/local/lib/python3.7/site-packages/aws_okta_processor/core/okta.py", line 76, in __init__
    user_pass=user_pass
  File "/usr/local/lib/python3.7/site-packages/aws_okta_processor/core/okta.py", line 146, in get_okta_single_use_token
    return self.handle_factor(response_json=response_json)
  File "/usr/local/lib/python3.7/site-packages/aws_okta_processor/core/okta.py", line 162, in handle_factor
    return self.verify_factor(factor=factor, state_token=state_token)
  File "/usr/local/lib/python3.7/site-packages/aws_okta_processor/core/okta.py", line 171, in verify_factor
    json_payload = factor.payload()
  File "/usr/local/lib/python3.7/site-packages/aws_okta_processor/core/okta.py", line 409, in payload
    return {"passCode": input()}
EOFError: EOF when reading a line
Password:
```
It prompts the password again and after entering it for the second time it throws the same error and dies:
```
Info: Calling https://company-name.okta.com/api/v1/authn
Token: Traceback (most recent call last):
  File "/usr/local/bin/aws-okta-processor", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/aws_okta_processor/cli.py", line 74, in main
    command.run()
  File "/usr/local/lib/python3.7/site-packages/aws_okta_processor/commands/authenticate.py", line 74, in run
    credentials = self.authenticate()
  File "/usr/local/lib/python3.7/site-packages/aws_okta_processor/commands/authenticate.py", line 68, in authenticate
    credentials = saml_fetcher.fetch_credentials()
  File "/usr/local/lib/python3.7/site-packages/aws_okta_processor/core/fetcher.py", line 38, in fetch_credentials
    credentials = super(SAMLFetcher, self).fetch_credentials()
  File "/Users/dizeee/Library/Python/3.7/lib/python/site-packages/botocore/credentials.py", line 629, in fetch_credentials
    return self._get_cached_credentials()
  File "/Users/dizeee/Library/Python/3.7/lib/python/site-packages/botocore/credentials.py", line 639, in _get_cached_credentials
    response = self._get_credentials()
  File "/usr/local/lib/python3.7/site-packages/aws_okta_processor/core/fetcher.py", line 62, in _get_credentials
    no_okta_cache=self._configuration["AWS_OKTA_NO_OKTA_CACHE"]
  File "/usr/local/lib/python3.7/site-packages/aws_okta_processor/core/okta.py", line 76, in __init__
    user_pass=user_pass
  File "/usr/local/lib/python3.7/site-packages/aws_okta_processor/core/okta.py", line 146, in get_okta_single_use_token
    return self.handle_factor(response_json=response_json)
  File "/usr/local/lib/python3.7/site-packages/aws_okta_processor/core/okta.py", line 162, in handle_factor
    return self.verify_factor(factor=factor, state_token=state_token)
  File "/usr/local/lib/python3.7/site-packages/aws_okta_processor/core/okta.py", line 171, in verify_factor
    json_payload = factor.payload()
  File "/usr/local/lib/python3.7/site-packages/aws_okta_processor/core/okta.py", line 409, in payload
    return {"passCode": input()}
EOFError: EOF when reading a line
Error response from daemon: Get https://XXXXXXXXXXXX.dkr.ecr.eu-central-1.amazonaws.com/v2/php/manifests/7.4-dev-latest: no basic auth credentials
```

`~/.aws/credentials` looks like this:
```
[my-profile]
credential_process=aws-okta-processor authenticate --organization company-name.okta.com --user me@company-name.com --role arn:aws:iam::XXXXXXXXXXXX:role/Administrator --key my-profile
```

**Comment by tahoward** [comment]
I took a look at this issue. This appears to be a problem with how docker executes external processes:
https://github.com/godaddy/aws-okta-processor/issues/23

**Comment by samuelkarp** [comment]
Hi @dizeee and @tahoward! The credential helper does not currently have a mechanism to prompt for input today. I'm going to mark this as an enhancement; there may need to be changes in the Docker CLI for allowing a credential helper to accept additional input.
