### ISSUE TITLE
creds not consumed via instance profile (kube2iam) with default AWS_SDK_LOAD_CONFIG=true

### ISSUE THREAD

**Issue by Constantin07** [awslabs/amazon-ecr-credential-helper#268]
I've got a service running in Kubernetes which uses `kube2iam` to provide an IAM role to a service via instance metadata.

Here are my configs:

~/.aws/config:
```
[default]
credential_source = Ec2InstanceMetadata
region = eu-west-1
output = json
```
~/.docker/config.json
```json
{
  "credHelpers": {
    "public.ecr.aws": "ecr-login",
    "**************.dkr.ecr.eu-west-1.amazonaws.com": "ecr-login",
    "489478819445.dkr.ecr.us-west-2.amazonaws.com": "ecr-login"
  }
}
```

Here is what happens:
```
docker pull ***************.dkr.ecr.eu-west-1.amazonaws.com/******************
panic: CredentialRequiresARNError: credential type credential_source requires role_arn, profile default

goroutine 1 [running]:
github.com/aws/aws-sdk-go/aws/session.Must(...)
	/go/pkg/mod/github.com/aws/aws-sdk-go@v1.36.0/aws/session/session.go:345
github.com/awslabs/amazon-ecr-credential-helper/ecr-login/api.DefaultClientFactory.NewClientFromRegion(0xc00003079d, 0x9, 0xfd4, 0xfd4)
	/go/src/github.com/awslabs/amazon-ecr-credential-helper/ecr-login/api/factory.go:90 +0x354
github.com/awslabs/amazon-ecr-credential-helper/ecr-login.ECRHelper.Get(0x9bcc80, 0xbfd238, 0xc0000286f0, 0x2c, 0xc00019fc48, 0x4502cf, 0xc0000286f0, 0xc000030740, 0x2c, 0xc0000286f0)
	/go/src/github.com/awslabs/amazon-ecr-credential-helper/ecr-login/ecr.go:63 +0x505
github.com/docker/docker-credential-helpers/credentials.Get(0x9bbfc0, 0xc00007d540, 0x9b5b40, 0xc00000e010, 0x9b5b60, 0xc00000e018, 0x10, 0x7f5b41437108)
	/go/pkg/mod/github.com/docker/docker-credential-helpers@v0.6.3/credentials/credentials.go:130 +0x1f7
github.com/docker/docker-credential-helpers/credentials.HandleCommand(0x9bbfc0, 0xc00007d540, 0x7ffe3051cd87, 0x3, 0x9b5b40, 0xc00000e010, 0x9b5b60, 0xc00000e018, 0xc00019ff48, 0xc00007d540)
	/go/pkg/mod/github.com/docker/docker-credential-helpers@v0.6.3/credentials/credentials.go:73 +0x125
github.com/docker/docker-credential-helpers/credentials.Serve(0x9bbfc0, 0xc00007d540)
	/go/pkg/mod/github.com/docker/docker-credential-helpers@v0.6.3/credentials/credentials.go:58 +0x1c5
main.main()
	/go/src/github.com/awslabs/amazon-ecr-credential-helper/ecr-login/cli/docker-credential-ecr-login/main.go:45 +0x14e
Error response from daemon: Head https://***************dkr.ecr.eu-west-1.amazonaws.com/v2/********************: no basic auth credentials
```

If I set `AWS_SDK_LOAD_CONFIG=false`, it works fine:
```bash
[Pipeline] sh
+ AWS_SDK_LOAD_CONFIG=false docker pull ************.dkr.ecr.eu-west-1.amazonaws.com/*******************:latest
latest: Pulling from **********************
801bfaa63ef2: Pulling fs layer
3c85d4dd6beb: Pulling fs layer
411beeea97f6: Pulling fs layer
1235ad9aa811: Pulling fs layer
1235ad9aa811: Waiting
411beeea97f6: Download complete
801bfaa63ef2: Verifying Checksum
801bfaa63ef2: Download complete
801bfaa63ef2: Pull complete
1235ad9aa811: Verifying Checksum
1235ad9aa811: Download complete
3c85d4dd6beb: Download complete
3c85d4dd6beb: Pull complete
411beeea97f6: Pull complete
1235ad9aa811: Pull complete
Digest: sha256:cd314caaaa2fb2e652e926d7bf36d5158c60ccf4cdc9131f43519d253b567b19
Status: Downloaded newer image for ************.dkr.ecr.eu-west-1.amazonaws.com/*******************:latest
```

ECR credentials helper version: `0.5.0`

Based on the doc page https://github.com/awslabs/amazon-ecr-credential-helper#aws-credentials the IAM role for EC2 is the last one in the list to be considered if the first ones are not available but it doesn't work unless I set `AWS_SDK_LOAD_CONFIG=false`.

1. Is that the expected behaviour ? Why it doesn't consume the role from metadata service by default with least priorily?
2. Should it really panic if local cred configuration not found ?

Thanks

**Comment by BeyondEvil** [comment]
I have this too, but with a custom `credential_process`.
