### ISSUE TITLE
Credential helper not compatible with configured sso-session

### ISSUE THREAD

**Issue by kwohlfahrt** [awslabs/amazon-ecr-credential-helper#522]
I have the following `~/.aws/config`, generated with the `aws configure sso` tool:

```ini
[default]
sso_session = default
sso_account_id = # SNIP
sso_role_name = AWSAdministratorAccess
region = eu-west-1
output = table

[sso-session default]
sso_start_url = # SNIP, not sure if this is sensitive
sso_region = eu-central-1
sso_registration_scopes = sso:account:access
```

Now, when I try to pull an image (after running `aws sso login`) from our internal repository using this tool, I get the following error:

```
Using default tag: latest
panic: profile "default" is configured to use SSO but is missing required configuration: sso_region, sso_start_url

goroutine 1 [running]:
github.com/awslabs/amazon-ecr-credential-helper/ecr-login/api.DefaultClientFactory.NewClientFromRegion({}, {0x1400013705d, 0xc})
	/go/src/github.com/awslabs/amazon-ecr-credential-helper/ecr-login/api/factory.go:84 +0x178
github.com/awslabs/amazon-ecr-credential-helper/ecr-login.ECRHelper.Get({{0x10054e9b8, 0x100783288}}, {0x1400012c4b0, 0x2f})
	/go/src/github.com/awslabs/amazon-ecr-credential-helper/ecr-login/ecr.go:63 +0x2f0
github.com/docker/docker-credential-helpers/credentials.Get({0x10054d1f0, 0x14000111160}, {0x100545240, 0x1400012e000}, {0x100545260, 0x1400012e008})
	/go/pkg/mod/github.com/docker/docker-credential-helpers@v0.6.3/credentials/credentials.go:130 +0x208
github.com/docker/docker-credential-helpers/credentials.HandleCommand({0x10054d1f0, 0x14000111160}, {0x16fc83abc, 0x3}, {0x100545240, 0x1400012e000}, {0x100545260, 0x1400012e008})
	/go/pkg/mod/github.com/docker/docker-credential-helpers@v0.6.3/credentials/credentials.go:73 +0x84
github.com/docker/docker-credential-helpers/credentials.Serve({0x10054d1f0, 0x14000111160})
	/go/pkg/mod/github.com/docker/docker-credential-helpers@v0.6.3/credentials/credentials.go:58 +0x124
main.main()
	/go/src/github.com/awslabs/amazon-ecr-credential-helper/ecr-login/cli/docker-credential-ecr-login/main.go:45 +0x1f0
Error response from daemon: Head "https://455661021047.dkr.ecr.eu-central-1.amazonaws.com/v2/ray-dragonligandfold/manifests/latest": no basic auth credentials
```

The following config, without the `[sso-session]` block, works fine:

```ini
[default]
sso_account_id = # SNIP
sso_role_name = AWSAdministratorAccess
region = eu-west-1
output = table
sso_start_url = # SNIP
sso_region = eu-central-1
sso_registration_scopes = sso:account:access
```

**Comment by austinvazquez** [comment]
Hi, @kwohlfahrt thanks for the feedback. I have looked into the issue and found the amazon-ecr-credential-helper relies on the the AWS Go SDK for configuration parsing. See [here](https://github.com/awslabs/amazon-ecr-credential-helper/blob/main/ecr-login/api/factory.go#L78) for the call.

I did some testing using mainline and found your configuration to work fine; however, when I downgraded the AWS Go SDK down to what is in v0.6.0 release found the issue you described above. So I believe what would help is to have an updated release. Let me try to work and allocate some bandwidth to help alleviate this pain for you.

In the meantime, if your use case allows building from source should give you the results you need.

**Comment by austinvazquez** [comment]
Special thanks to @fangn2 for working to push this item through. v0.7.0 is available with fix for the issue.

cc: @kwohlfahrt
